[package]
name = "patternscanner"
version = "0.0.0"
edition = "2021"
description = "A high performance multithreaded pattern scanner for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1"