name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Clippy
        run: cargo clippy

      - name: Build
        run: cargo build --verbose

      - name: Tests
        run: cargo test --verbose
